name: Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-binaries:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pyinstaller
      - name: Build binary
        shell: bash
        run: |
          pyinstaller --name corpus --onefile --console -F -p corpus corpus/__main__.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: corpus-${{ runner.os }}
          path: dist/*


